version: 2.1

parameters:
  service2-my-name:
    type: string
    default: "world"

jobs:
  service2-say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      MY_NAME: << pipeline.parameters.service1-my-name >>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, ${MY_NAME}!2"

workflows:
  service2-say-hello-workflow:
    jobs:
      - common-say-hello
      - service2-say-hello
